_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 51
                - 53
                - 54
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 35
                - 49
                - 51
                - 53
                - 54
                - 55
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.2
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
alpha:
    value: 1
batch_size:
    value: 1024
clusteralg:
    value: louvain
corrupt:
    value: 0.25
dec_epoch:
    value: 6000
dec_gamma:
    value: 0.2
dec_lr:
    value: 0.005
dec_step_size:
    value: 2000
dims:
    value:
        - 313
        - 228
        - 114
        - 20
finetune_epoch:
    value: 500
n_cluster:
    value: 19
num_workers:
    value: 0
plot:
    value: false
pretrain_epoch:
    value: 1000
pretrain_gamma:
    value: 0.8
pretrain_lr:
    value: 0.0001
pretrain_momentum:
    value: 0.9
pretrain_step_size:
    value: 100
reduce_dim:
    value: pca
stopping_delta:
    value: 1e-07
train_gamma:
    value: 0.8
train_lr:
    value: 0.001
train_momentum:
    value: 0.8
train_step_size:
    value: 100
